#!/bin/sh
#
# nginx - this script starts and stops the nginx daemon
#
# chkconfig:   - 85 15
# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: nginx
# config:      /usr/local/ngx_http_rd/conf/nginx.conf
# config:      /etc/sysconfig/ngx_http_rd
# pidfile:     /var/run/nginx.pid
pidfile=/var/run/nginx.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

[ -f /etc/sysconfig/ngx_http_rd ] && . /etc/sysconfig/ngx_http_rd

nginx=${NGINX-/usr/local/ngx_http_rd/sbin/nginx}
prog=$(basename $nginx)

conffile=${NGINX_CONF_FILE-/usr/local/ngx_http_rd/conf/nginx.conf}

lockfile=/var/lock/subsys/ngx_http_rd

start() {
    [ -x $nginx ] || exit 5
    [ -f $conffile ] || exit 6
    echo -n $"Starting $prog: "
    daemon --pidfile=${pidfile} $nginx -c $conffile
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
#    $nginx -c $conffile && touch $lockfile
#    echo Started.
#    return 0
}

stop() {
    echo -n $"Stopping $prog: "
    #killproc $prog
    killproc -p ${pidfile} $nginx
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    configtest_q || configtest || return 6
    stop
    start
}

reload() {
    configtest_q || configtest || return 6
    echo -n $"Reloading $prog: "
    killproc $nginx -HUP
    echo
}

configtest() {
  $nginx -t -c $conffile
}

configtest_q() {
    configtest >/dev/null 2>&1
}

rh_status() {
#    status $prog
    status $nginx
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

# Upgrade the binary with no downtime.
upgrade() {
    local pidfile="/var/run/nginx.pid"
    local oldbin_pidfile="${pidfile}.oldbin"

    configtest_q || configtest || return 6
    echo -n $"Staring new master $prog: "
    killproc $nginx -USR2
    retval=$?
    echo 
    sleep 1
    if [[ -f ${oldbin_pidfile} && -f ${pidfile} ]];  then
        echo -n $"Graceful shutdown of old $prog: "
        killproc -p ${oldbin_pidfile} -QUIT
        retval=$?
        echo 
        return 0
    else
        echo $"Something bad happened, manual intervention required, maybe restart?"
        return 1
    fi
}

case "$1" in
    start)
#        rh_status_q && exit 0
        $1
        ;;
    stop)
#        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    force-reload|upgrade) 
        rh_status_q || exit 7
        upgrade
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    status|status_q)
        rh_$1
        ;;
    condrestart|try-restart)
        rh_status_q || exit 7
        restart
	    ;;
    *)
        echo $"Usage: $0 {start|stop|reload|configtest|status|force-reload|upgrade|restart}"
        exit 2
esac
